### ISSUE TITLE
Todo List from Meeting 

### ISSUE THREAD

**Issue by tubiana** [reuter-group/peprmint-web#5]
- [x] PePr2DS: Title: PePr2DS (remove “Peripheral Protein Protrusion Dataset”) - DX
- [ ] PePr2DS: Text to explain what it is the website about and link to a longer description -  TT, NR, DX
- [x] PePr2DS: Protein Domain -> tooltip that give the list of domains (parsed from statistics.json?) - DX  
- [ ] PePr2DS: Make picture to explain what is the IBS and what is a protrusion - TT
- [ ] PePrMInt-Web:  Front page -> Before the two tools, text explaining PePr2Vis and PePr2DS - TT, NR, DX
- [ ] PePrMInt-Web:  Front page -> only keep my name on the pictures - TT
- [ ] PePr2DS:  Make a protrusion figure (just like Nathalie Grant) - TT
- [x] PePr2DS: Remove AlphaFold structures - TT
- [x] PePr2DS: Remove neighbourhood residues for convexhull vertices only (keep for protrusions) - TT
- [x] Removing the visualisation of the `PDB` with PePr2Vis, instead link to the PDB webpage - DX

Corrections:

- [x] PePr2DS: "items" --> Amino acid - DX, TT
- [x] PePr2DS: "Complete Dataset" --> "Whole Dataset"- DX, TT
- [x] PePr2DS: "Download (.csv) --> "Download Selection(.csv)"- DX, TT
- [x] PePr2DS: Graph: "Residue Composition" --> "Your selection composition"- DX, TT

**Comment by Ginko-X** [comment]
should we also decide the color theme for the chart?

**Comment by Ginko-X** [comment]
I have adjusted the text/layout as we discussed yesterday (not exactly as you write in the tasks above, but the same effect), and I have added placeholders so you can add the text description
